trigger:
  branches : 
   include : 
    - main

pool :
vmImage: 'ubuntu-latest'

variables :
	buildConfiguration : 'Release'

steps : 
	- task : DotNetCoreCLI@2
	displayname : Restore
	inputs : 
		command : restore
		projects : '**/*.csproj'

	-task : DotNetCoreCLI@2
	 displayname : Build
		inputs : build
		projects : '**/*.csproj'
		arguments : '--configuration $(buildConfiguration)'
